version: '3.8'  
  
services:  
  sarcasm-detector:  
    build:  
      context: .  
      dockerfile: docker/Dockerfile  
    ports:  
      - "8000:8000"  
    environment:  
      - ENVIRONMENT=production  
    restart: unless-stopped 
